name: Test Self Hosted Runner

on:
  push:
    branches:
      - feature/106

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Runner
        run: |
          echo "Hello from GitHub Actions"
          echo "Runner name: $env:RUNNER_NAME"
          hostname
          whoami
